<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-SQL-Journey/blob/main/Day06_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display only the employee_id first_name columns from the first 5 rows of the employees table
pd.read_sql("""
SELECT employee_id, first_name
FROM employees
LIMIT 5;
""", conn)

   employee_id first_name
0            1      Aarav
1            2     Vivaan
2            3     Aditya
3            4       Riya
4            5      Priya

In [ ]:
#Display department_id and department_name from the first 4 departments
pd.read_sql("""
SELECT department_id, department_name
FROM departments
LIMIT 4;
""", conn)

   department_id department_name
0              1              HR
1              2         Finance
2              3              IT
3              4       Marketing

In [ ]:
#Display product_id, product_name and price from the first 6 products
pd.read_sql("""
SELECT product_id, product_name, price
FROM products
LIMIT 6;
""", conn)

   product_id    product_name    price
0           1  Laptop Model 1  90499.0
1           2  Laptop Model 2  90999.0
2           3  Laptop Model 3  91499.0
3           4  Laptop Model 4  91999.0
4           5  Mobile Model 1  30499.0
5           6  Mobile Model 2  30999.0

In [ ]:
#Diplay customer_id, customer_name and city from the first 8 customers
pd.read_sql("PRAGMA table_info(customers);", conn)

   cid         name     type  notnull dflt_value  pk
0    0  customer_id  INTEGER        0       None   1
1    1   first_name     TEXT        0       None   0
2    2    last_name     TEXT        0       None   0
3    3        email     TEXT        0       None   0
4    4        phone     TEXT        0       None   0
5    5         city     TEXT        0       None   0

In [ ]:
#Display order_id, customer_id, employee_id and order_date from the first 10 orders
pd.read_sql("PRAGMA table_info(orders);", conn)

   cid         name     type  notnull dflt_value  pk
0    0     order_id  INTEGER        0       None   1
1    1  customer_id  INTEGER        0       None   0
2    2   product_id  INTEGER        0       None   0
3    3   order_date     TEXT        0       None   0
4    4     quantity  INTEGER        0       None   0

In [ ]:
#Display the first 5 rows from the products table showing only product_name and category
pd.read_sql("""
SELECT product_name, category
FROM products
LIMIT 5;
""", conn)

     product_name category
0  Laptop Model 1   Laptop
1  Laptop Model 2   Laptop
2  Laptop Model 3   Laptop
3  Laptop Model 4   Laptop
4  Mobile Model 1   Mobile