<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day17_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display employees whose employee_id is BETWEEN 1 AND 5
pd.read_sql("""
SELECT *
FROM employees
WHERE employee_id BETWEEN 1 AND 5;
""", conn)

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com
1,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
2,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
3,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
4,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com

In [ ]:
#Display customers whose city is IN (Bangalore, Mumbai)
pd.read_sql("""
SELECT *
FROM customers
WHERE city IN ('Bangalore', 'Mumbai');
""", conn)

   customer_id first_name last_name              email       phone       city
0            1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1            2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
2            3      Mohit     Kumar    mohit3@mail.com  9208428912     Mumbai
3           11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
4           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore
5           28      Komal     Singh   komal28@mail.com  9110051432     Mumbai
6           30      Aisha       Das   aisha30@mail.com  9627755893     Mumbai

In [ ]:
#Display products whose category is NOT Electronics
pd.read_sql("""
SELECT *
FROM products
WHERE NOT category = 'Electronics';
""", conn)

    product_id        product_name    category    price  stock_quantity
0            1      Laptop Model 1      Laptop  90499.0              35
1            2      Laptop Model 2      Laptop  90999.0               0
2            3      Laptop Model 3      Laptop  91499.0              50
3            4      Laptop Model 4      Laptop  91999.0               5
4            5      Mobile Model 1      Mobile  30499.0              35
5            6      Mobile Model 2      Mobile  30999.0               0
6            7      Mobile Model 3      Mobile  31499.0              12
7            8      Mobile Model 4      Mobile  31999.0               0
8            9  Headphones Model 1  Headphones   5499.0              80
9           10  Headphones Model 2  Headphones   5999.0               0
10          11  Headphones Model 3  Headphones   6499.0              80
11          12  Headphones Model 4  Headphones   6999.0               5
12          13     Monitor Model 1     Monitor  16499.0              20
13          14     Monitor Model 2     Monitor  16999.0               0
14          15     Monitor Model 3     Monitor  17499.0               5
15          16     Monitor Model 4     Monitor  17999.0              20
16          17    Keyboard Model 1    Keyboard   2499.0              80
17          18    Keyboard Model 2    Keyboard   2999.0              35
18          19    Keyboard Model 3    Keyboard   3499.0               5
19          20    Keyboard Model 4    Keyboard   3999.0              50
20          21       Mouse Model 1       Mouse   1499.0               0
21          22       Mouse Model 2       Mouse   1999.0              20
22          23       Mouse Model 3       Mouse   2499.0              35
23          24       Mouse Model 4       Mouse   2999.0               0
24          25      Camera Model 1      Camera  46499.0               0

In [ ]:
#Display orders whose customer_id IN (1,2,3) AND order_id BETWEEN 1
pd.read_sql("""
SELECT *
FROM orders
WHERE customer_id IN (1, 2, 3)
AND order_id BETWEEN 1 AND 20;
""", conn)

   order_id  customer_id  product_id  order_date  quantity
0         7            2          20  2024-05-15         2
1        10            1          10  2024-07-16         5

In [ ]:
#Display employee_id, first_name, last_name for employees whose department_id IN (1,2) AND employee_id BETWEEN