<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day16_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display product whose price is BETWEEN 1000 AND 5000
pd.read_sql("""
SELECT *
FROM products
WHERE price BETWEEN 1000 AND 5000;
""", conn)

   product_id      product_name  category   price  stock_quantity
0          17  Keyboard Model 1  Keyboard  2499.0              80
1          18  Keyboard Model 2  Keyboard  2999.0              35
2          19  Keyboard Model 3  Keyboard  3499.0               5
3          20  Keyboard Model 4  Keyboard  3999.0              50
4          21     Mouse Model 1     Mouse  1499.0               0
5          22     Mouse Model 2     Mouse  1999.0              20
6          23     Mouse Model 3     Mouse  2499.0              35
7          24     Mouse Model 4     Mouse  2999.0               0

In [ ]:
#Display customer whose employee_id is BETWEEN 3 AND 8
pd.read_sql("""
SELECT *
FROM employees
WHERE employee_id BETWEEN 3 AND 8;
""", conn)

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
1,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
2,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
3,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com
4,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
5,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com

In [ ]:
#Display customers whose customer_id is BETWEEN 2 AND 6
pd.read_sql("""
SELECT *
FROM customers
WHERE customer_id BETWEEN 2 AND 6;
""", conn)

   customer_id first_name last_name             email       phone       city
0            2       Ritu       Das    ritu2@mail.com  9627404182  Bangalore
1            3      Mohit     Kumar   mohit3@mail.com  9208428912     Mumbai
2            4     Simran       Das  simran4@mail.com  9979444461    Chennai
3            5       Yash    Sharma    yash5@mail.com  9426111115       Pune
4            6     Anjali     Singh  anjali6@mail.com  9693986973       Pune

In [ ]:
#Display orders whose order_id is BETWEEN 5 AND 15
pd.read_sql("""
SELECT *
FROM orders
WHERE order_id BETWEEN 5 AND 15;
""", conn)

    order_id  customer_id  product_id  order_date  quantity
0          5           16           3  2024-12-14         1
1          6           15          20  2025-09-01         2
2          7            2          20  2024-05-15         2
3          8           13          19  2026-03-11         1
4          9           28           7  2025-01-10         1
5         10            1          10  2024-07-16         5
6         11           13          14  2024-12-19         2
7         12           26          16  2025-12-07         1
8         13           14          17  2026-04-14         5
9         14           33          19  2024-01-19         1
10        15           27           2  2024-10-16         2

In [ ]:
#Display employee_id, first_name and last_name for employees whose department_id is 2 AND employee_id is BETWEEN 2 AND 10