<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day18_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display employees whose employee_id is BETWEEN 4 AND 8
pd.read_sql("""
SELECT *
FROM employees
WHERE employee_id BETWEEN 4 AND 8;
""", conn)

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
1,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
2,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com
3,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
4,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com

In [ ]:
#Display customers whose city is NOT "Bangalore"
pd.read_sql("""
SELECT *
FROM customers
WHERE NOT city = 'Bangalore';
""", conn)

    customer_id first_name last_name              email       phone       city
0             3      Mohit     Kumar    mohit3@mail.com  9208428912     Mumbai
1             4     Simran       Das   simran4@mail.com  9979444461    Chennai
2             5       Yash    Sharma     yash5@mail.com  9426111115       Pune
3             6     Anjali     Singh   anjali6@mail.com  9693986973       Pune
4             7     Deepak    Wilson   deepak7@mail.com  9906274295  Hyderabad
5             8      Komal       Roy    komal8@mail.com  9467566361      Delhi
6             9      Nitin     Brown    nitin9@mail.com  9899533704  Hyderabad
7            10      Aisha     Kumar   aisha10@mail.com  9332083015    Chennai
8            12       Ritu     Kumar    ritu12@mail.com  9658448295      Delhi
9            13      Mohit       Das   mohit13@mail.com  9361812679  Hyderabad
10           14     Simran    Taylor  simran14@mail.com  9604314504    Kolkata
11           15       Yash    Sharma    yash15@mail.com  9702952921  Hyderabad
12           17     Deepak    Taylor  deepak17@mail.com  9865412201  Hyderabad
13           18      Komal     Singh   komal18@mail.com  9504584808    Kolkata
14           19      Nitin    Taylor   nitin19@mail.com  9995653703  Hyderabad
15           20      Aisha     Kumar   aisha20@mail.com  9659589923      Delhi
16           21      Akash    Sharma   akash21@mail.com  9124393190       Pune
17           22       Ritu     Kumar    ritu22@mail.com  9882449902  Hyderabad
18           23      Mohit    Taylor   mohit23@mail.com  9744597750    Kolkata
19           24     Simran       Das  simran24@mail.com  9185583902       Pune
20           25       Yash     Singh    yash25@mail.com  9834197053       Pune
21           26     Anjali     Kumar  anjali26@mail.com  9988357959      Delhi
22           27     Deepak    Sharma  deepak27@mail.com  9922832851      Delhi
23           28      Komal     Singh   komal28@mail.com  9110051432     Mumbai
24           29      Nitin    Wilson   nitin29@mail.com  9200774016  Hyderabad
25           30      Aisha       Das   aisha30@mail.com  9627755893     Mumbai
26           31      Akash     Gupta   akash31@mail.com  9750806415    Kolkata
27           32       Ritu    Sharma    ritu32@mail.com  9787498671    Chennai
28           33      Mohit       Roy   mohit33@mail.com  9665152033      Delhi
29           34     Simran    Wilson  simran34@mail.com  9642604350       Pune
30           35       Yash       Das    yash35@mail.com  9847568100  Hyderabad
31           36     Anjali     Gupta  anjali36@mail.com  9310837702    Chennai
32           37     Deepak    Wilson  deepak37@mail.com  9413891625       Pune
33           38      Komal       Roy   komal38@mail.com  9634822466    Chennai
34           39      Nitin       Das   nitin39@mail.com  9759424149    Chennai
35           40      Aisha    Taylor   aisha40@mail.com  9829603810    Kolkata

In [ ]:
#Display products whose category is IN (Electronics Furniture) AND price BETWEEN 1000 and 5000
pd.read_sql("""
SELECT *
FROM products
WHERE category IN ('Electronics', 'Furniture')
AND price BETWEEN 1000 AND 5000;
""", conn)

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [ ]:
#Display orders where customer_id IN (2,3) OR employee_id = 1
pd.read_sql("""
SELECT *
FROM orders
WHERE customer_id IN (2, 3)
OR order_id = 1;
""", conn)

   order_id  customer_id  product_id  order_date  quantity
0         1           20           2  2025-10-15         4
1         7            2          20  2024-05-15         2
2        52            2          23  2026-01-31         4
3        66            2           3  2024-08-03         4
4        80            3           6  2024-01-26         2
5        84            3           4  2025-06-19         1
6        89            3           1  2026-03-29         1

In [ ]:
#Display employee_id, first_name and last_name for employees whose department_id IN (1,2) AND employee_id NOT BETWEEN 1 AND 3
pd.read_sql("""
SELECT employee_id, first_name, last_name
FROM employees
WHERE department_id IN (1, 2)
AND employee_id NOT BETWEEN 1 AND 3;
""", conn)

   employee_id first_name last_name
0           11       Noah     Singh
1           12     Olivia       Roy
2           21      Arjun    Taylor
3           22       Isha       Roy