<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-SQL-Journey/blob/main/Day10_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display unique department names from the departments table
pd.read_sql("""
SELECT DISTINCT department_name
FROM departments;
""", conn)

    department_name
0                HR
1           Finance
2                IT
3         Marketing
4             Sales
5        Operations
6           Support
7             Legal
8  Data Engineering
9          Security

In [ ]:
#Display unique city values from the customers table
pd.read_sql("""
SELECT DISTINCT city
FROM customers;
""", conn)

        city
0  Bangalore
1     Mumbai
2    Chennai
3       Pune
4  Hyderabad
5      Delhi
6    Kolkata

In [ ]:
#Display unique category values from products table
pd.read_sql("""
SELECT DISTINCT category
FROM products;
""", conn)

     category
0      Laptop
1      Mobile
2  Headphones
3     Monitor
4    Keyboard
5       Mouse
6      Camera

In [ ]:
#Display the first 5 unique employee job titles (or another repeating employee attribute if available)
pd.read_sql("""
SELECT DISTINCT job_title
FROM employees
LIMIT 5;
""", conn)

             job_title
0         HR Executive
1           Accountant
2    Software Engineer
3  Marketing Executive
4      Sales Executive

In [ ]:
#Display the first 10 unique customer cities using DISTINCT AND LIMIT
pd.read_sql("""
SELECT DISTINCT city
FROM customers
LIMIT 10;
""", conn)

        city
0  Bangalore
1     Mumbai
2    Chennai
3       Pune
4  Hyderabad
5      Delhi
6    Kolkata