<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-SQL-Journey/blob/main/Day11_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display all details of the employees whose employee_id is 1
pd.read_sql("""
SELECT *
FROM employees
WHERE employee_id = 1;
""", conn)

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com

In [10]:
#Display all products whose category is "Electronics"
pd.read_sql("""
SELECT *
FROM products
WHERE category = 'Electronics';
""", conn)

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [ ]:
#Display all customers who belong to the city "Bangalore"
pd.read_sql("""
SELECT *
FROM customers
WHERE city = 'Bangalore';
""", conn)

   customer_id first_name last_name              email       phone       city
0            1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1            2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
2           11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
3           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore

In [ ]:
#Display all orders placed by customer_id
pd.read_sql("""
SELECT *
FROM orders
WHERE customer_id = 1;
""", conn)

   order_id  customer_id  product_id  order_date  quantity
0        10            1          10  2024-07-16         5

In [ ]:
#Display first_name, last_name and email of employees who belong to department_id 2
pd.read_sql("""
SELECT first_name, last_name, email
FROM employees
WHERE department_id = 2;
""", conn)

  first_name last_name                      email
0     Vivaan     Patel  vivaan.patel2@company.com
1     Olivia       Roy   olivia.roy12@company.com
2       Isha       Roy     isha.roy22@company.com